### ISSUE TITLE
Files are not showing from different latest tag in web

### ISSUE THREAD

**Issue by FcoCalero** [catay/rrst#9]
Opening the url in the web browser, it doesn't show files from specific tag, it only shows always the latest tag files.

**Comment by catay** [comment]
What counts is the RPM-MD metadata.  That's what tools like (Dandified) YUM and zypper use to fetch the right package versions.  I consider this not an issue as it's part of how it's designed.

What can be done is implement a `rrst diff <revision 1|tag 1> <revision 2|tag2>` command that lists the package differences between two revisions.

**Comment by FcoCalero** [comment]
It sounds great, that way you won't have to go to the file folder for checking files or zypper. Thanks

**Comment by catay** [comment]
I consider this fixed now.  The 'status' command replaced the 'list' command.
Check out the new 'list' and 'diff' command to list the package versions of a set of repository tags or revisions.
